INSERT INTO tb_category (name, created_At) VALUES ('Home Appliances', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Furniture', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Toys', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Sports', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Beauty', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Health', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Automotive', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Garden', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Office Supplies', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Pet Supplies', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Groceries', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Music', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Movies', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Video Games', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Jewelry', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Watches', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Shoes', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Bags', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Accessories', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Stationery', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Art Supplies', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Crafts', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Photography', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Travel', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Baby Products', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Cleaning Supplies', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Lighting', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Hardware', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Building Materials', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Industrial Supplies', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Medical Supplies', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Outdoor Equipment', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Camping Gear', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Fitness Equipment', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Cycling', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Fishing', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Hiking', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Drones', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Smart Home Devices', NOW());